config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contacts

  devise_scope :user do
    get "/logout" => "devise/sessions#destroy"
  end

  #root 'devise/sessions#new'

  #root  'devise/registrations#new'

  root 'home#index'



  get 'home/about'
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class 
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
    has_many :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


def after_sign_out_path_for(resource_or_scope)
 new_user_registration_path
end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    #@contact = Contact.new
    @contact = current_user.contact.build

  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    #@contact = Contact.new(contact_params)
    @contact = current_user.contact.build(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not Authorized To Edit This Friend" if @contact.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number, :email, :website, :adress, :notes, :user_id) 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">

<div class="card d-flex justify-content-center"style="width: 20rem;" >

  <div class="card-header bg-primary fs-1 text-info fw-bolder m-2">
    <%= contact.first_name %>
    <%= contact.last_name %>
  </div>

  <div class="card-body ">
  
    <p>
      <strong>Phone number:</strong>
      <%= contact.phone_number %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= contact.email %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= contact.website %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= contact.adress %>
    </p>

    <p>
      <strong>Notes:</strong>
      <%= contact.notes %>
    </p>

  
  </div>
</div>


</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-3">
    <p class="m-3"> 
      <%= form.label :first_name, style: "display: block", class:"fw-bold" %>
      <%= form.text_field :first_name, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" first name" %>
    </p>
    <p class="m-3"> 
      <%= form.label :last_name, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_field :last_name, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" last name"%>
    </p>
    <p class="m-3"> 
      <%= form.label :phone_number, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_field :phone_number, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" phone number" %>
    </p>

    <p class="m-3">
      <%= form.label :email, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_field :email, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" email"  %>
    </p>
    <p class="m-3">
      <%= form.label :website, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_field :website, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" website" %>
    </p>
    <p class="m-3">
      <%= form.label :address, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_field :adress, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" address" %>
    </p>
 
    <p class="m-3">
      <%= form.label :notes, style: "display: block",  class:"fw-bold"  %>
      <%= form.text_area :notes, class:"fw-light border border-1 rounded-1 border-primary shadow", placeholder:" notes" %>
    </p>

    <p class="m-3">
     <%= form.number_field :user_id, id: :index_contacts_on_user_id, value: current_user.id, type: :hidden %>
    </p>
    
  </div>


  <div>
    <%= form.submit class:"btn btn-secondary enable-shadows shadow border border-3 border-primary border-top-0 border-end-0 border-start-0 mb-3" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Book Entry</h1>

<%= render "form", contact: @contact %>
<br>

<div >
  <%= link_to "Show entry", @contact, class:"btn btn-info m-2 border rounded-1 shadow lg-info border-1 border-primary" %> |
  <%= link_to "Back to book", contacts_path, class:"btn btn-info m-2 border rounded-1 shadow lg-info border-1 border-primary" %>
</div>

app/views/contacts/index.html.erb
<% if user_signed_in? %>
<h1 class="m-3  text-primary fw-bolder text-center fst-italic"> Contacts Book </h1>


<div id="contacts" style="background:#e1f5fe; box-shadow: 3px 3px 15px 5px lightblue;" class="card p-3 border border-light"> 

<table class="table table-dark table-striped table-hover"> 

  <thead class="table-secondary text-dark">
    <tr>
      <th>Name</th>
      <th>Phone number</th>
      <th>Notes</th> 
      <th>More</th>
    </tr>

  </thead>

  <tbody>
  <% @contacts.each do |contact| %>
    <!-- <%= render contact  %> -->
    <% if contact.user == current_user %>
    <tr>
      <td>
        <%= link_to contact.first_name + ' ' + contact.last_name, contact,  class:"text-decoration-none text-info" %>
      </td>
      <td>
        <%= contact.phone_number %>
      </td>
       <td>
        <%= contact.notes %>
      </td>
       <td>
        <%= link_to "More", contact,  class:"text-decoration-none text-info" %>
      </td>
 
    </tr>
    <% end %>
    <% end %>
  </tbody>

  </table>
  
</div>

<p class="mt-5 "> 
<%= link_to "New contact", new_contact_path, class:"fw-bolder btn btn-secondary text-decoration-none enable-shadows shadow  border border-3 border-info border-top-0 border-end-0 border-start-0" %>
</p>

<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

app/views/contacts/show.html.erb
<!-- First Component -->
<div class="d-flex align-items-center mb-5" style="margin-top: 50px;"> 

<!-- Card for Contact full information -->
  <div class="card p-3 " style="background:#e1f5fe; box-shadow: 3px 3px 15px 5px lightblue;"> 
    <%= render @contact %> 

    <div class="d-flex align-self-start">
      <%= link_to "Edit", edit_contact_path(@contact), class:"m-2 btn btn-info text-decoration-none enable-shadows shadow border border-3 border-primary border-top-0 border-end-0 border-start-0" %> 

      <%= button_to "Delete", @contact, method: :delete, form: { data: { turbo_confirm: "Delete this contact?" } }, class:"m-2 btn btn-info text-decoration-none enable-shadows shadow border border-3 border-primary border-top-0 border-end-0 border-start-0" %>
      
      <%= link_to "Back to book", contacts_path, class:"m-2 btn btn-info enable-shadows shadow  border border-3 border-primary border-top-0 border-end-0 border-start-0" %> 
    </div>


  </div>
 
</div>

app/views/home/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white mt-auto" >
   <!-- Grid container -->
  <div class="container p-4">
    <h5 class="text-uppercase">My Contacts Book</h5>
  </div>

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://edelin11.github.io/EdelinPortfolios/">E.Portfolio</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/home/_header.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    
     <%= link_to 'ContactsBook', root_path, class:"navbar-brand" %>

  <% if user_signed_in? %>

    <%= link_to 'Book', contacts_path, class:"navbar-brand" %>
   

  <p>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample">
      <span class="navbar-toggler-icon"></span>
    </button>
  </p>

    <div class="collapse navbar-collapse" id="collapseExample">
    
   <li class="nav-item">
      <%= link_to 'New Contact', new_contact_path, class:"navbar-brand" %>
    </li>

    <li class="nav-item">
      <%= link_to 'My Account', edit_user_registration_path, class:"navbar-brand" %>
    </li>

    <li class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, 'data-turbo-method': :delete, class:"navbar-brand" %>
    </li>  
 <% end %>
    </div>

   

  </div>

</nav>

app/views/home/about.html.erb
<h1 class="container text-primary w-25 text-center fw-bold">Art News</h1>

app/views/home/index.html.erb
<h1 class="container text-primary w-50 text-center fw-bold">Contacts Book</h1>

<div class="d-flex flex-column justify-content-center text-center mb-3 p-3">
  <% if current_user %>
    <h3 class="text-center m-2">Welcome <%= current_user.email %>, </h3> 

    <h5 class="text-center m-2"> You have successfully loged in. </h5>

    <h4 class="text-center mt-4">Go to</h4>
    
    <p> 
      <%= link_to 'New Contact', new_contact_path, class:"btn btn-info m-2 border rounded-1 shadow lg-info border-1 border-primary" %> |
      <%= link_to "Contacts book", contacts_path, class:"btn btn-info m-2 border rounded-1 shadow lg-info border-1 border-primary" %>
    </p>

    



  <% else %>
    <p class="card border border-1 border-white d-flex text-center justify-content-center ">Welcome to Contacts Book <br/> This is a website where you can create a contacts list and not only that but you can also use our site to store passwords and links to websites or social media links.
      <h6 class="mt-5">Go ahead and click the link below to login or register if you haven't already.</h6>
      <%= link_to 'Sign In or Register', new_user_registration_path, class:"text-primary text-center fw-bold mt-5" %>
    </p>
  <% end %>

</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   <title>ContactsBook</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


  </head>
  <body class="d-flex flex-column min-vh-100">

    <%= render 'home/header' %>
    <div class="container p-3">

      <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>

      <br>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>

  


  </body>


</html>